import 'models.dart';

class MenuItem extends Equatable {
  final int id;
  final int restaurantId;
  final String name;
  final String category;
  final String description;
  final double price;

  const MenuItem({
    required this.id,
    required this.restaurantId,
    required this.name,
    required this.category,
    required this.description,
    required this.price,
  });

  @override
  List<Object?> get props => [
        id,
        restaurantId,
        name,
        category,
        description,
        price,
      ];

  static List<MenuItem> menuItems = [
    const MenuItem(
      id: 1,
      restaurantId: 1,
      name: 'Margherita',
      category: 'Pizza',
      description: 'Tomatoes, mozzarella, basil',
      price: 4.99,
    ),
    const MenuItem(
      id: 2,
      restaurantId: 1,
      name: '4 Formaggi',
      category: 'Pizza',
      description: 'Tomatoes, mozzarella, basil',
      price: 4.99,
    ),
    const MenuItem(
        id: 3,
        restaurantId: 1,
        name: 'Buddy Meal',
        description: '2 Classic Chicken Zingers & Medium Popcorn',
        price: 530,
        category: 'Fast Food'),
    const MenuItem(
        id: 4,
        restaurantId: 1,
        name: 'Pepsi',
        description: 'Cold BEverage',
        price: 50,
        category: 'Drinks'),
    const MenuItem(
      id: 5,
      restaurantId: 2,
      name: 'Strawberry Shake',
      description: 'Refreshing strawberry flavored shake',
      price: 150,
      category: 'Shakes',
    ),
    const MenuItem(
      id: 6,
      restaurantId: 2,
      name: 'Chocolate Shake',
      description: 'Indulgent chocolate flavored shake',
      price: 150,
      category: 'Shake',
    ),
    const MenuItem(
      id: 7,
      restaurantId: 2,
      name: 'Vanilla Shake',
      description: 'Creamy vanilla flavored shake',
      price: 150,
      category: 'Shake',
    ),
    const MenuItem(
      id: 8,
      restaurantId: 2,
      name: 'Coca-Cola',
      description: 'Classic cola beverage',
      price: 50,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 9,
      restaurantId: 2,
      name: 'Sprite',
      description: 'Lemon-lime flavored soda',
      price: 50,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 10,
      restaurantId: 3,
      name: 'Loaded Fries',
      description: 'Crispy fries topped with cheese, bacon, and jalapenos',
      price: 199,
      category: 'Fast Food',
    ),
    const MenuItem(
      id: 11,
      restaurantId: 3,
      name: 'Cheeseburger',
      description: 'Juicy beef patty with melted cheese and veggies',
      price: 249,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 12,
      restaurantId: 3,
      name: 'Chicken Burger',
      description: 'Tender grilled chicken fillet with lettuce and mayo',
      price: 229,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 13,
      restaurantId: 3,
      name: 'Veggie Burger',
      description: 'Delicious vegetarian patty with fresh toppings',
      price: 199,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 14,
      restaurantId: 4,
      name: 'Pizza Margherita',
      description: 'Classic cheese and tomato pizza',
      price: 350.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 15,
      restaurantId: 4,
      name: 'Pizza Pepperoni',
      description: 'Pizza with pepperoni toppings',
      price: 300.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 16,
      restaurantId: 4,
      name: 'Pizza Vegetarian',
      description: 'Pizza with assorted vegetables',
      price: 250.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 17,
      restaurantId: 4,
      name: 'Coca-Cola',
      description: 'Classic cola beverage',
      price: 49.99,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 18,
      restaurantId: 4,
      name: 'Sprite',
      description: 'Lemon-lime flavored soda',
      price: 49.99,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 19,
      restaurantId: 5,
      name: 'Chicken Biryani',
      description: 'Flavorful rice dish with tender chicken pieces',
      price: 249,
      category: 'Biriyani',
    ),
    const MenuItem(
      id: 20,
      restaurantId: 5,
      name: 'Fried Rice',
      description: 'Stir-fried rice with vegetables and choice of protein',
      price: 199,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 21,
      restaurantId: 5,
      name: 'Mango Lassi',
      description: 'Refreshing mango yogurt drink',
      price: 99,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 22,
      restaurantId: 5,
      name: 'Hummus',
      description: 'Traditional Middle Eastern chickpea dip',
      price: 149,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 23,
      restaurantId: 5,
      name: 'Paneer Tikka',
      description: 'Marinated cottage cheese cubes grilled to perfection',
      price: 199,
      category: 'Veg',
    ),
    const MenuItem(
      id: 24,
      restaurantId: 6,
      name: 'Hummus',
      description: 'Traditional Middle Eastern chickpea dip',
      price: 150.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 25,
      restaurantId: 6,
      name: 'Falafel',
      description: 'Deep-fried balls or patties made from ground chickpeas',
      price: 180.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 26,
      restaurantId: 6,
      name: 'Shawarma',
      description: 'Thinly sliced meat wrapped in a flatbread',
      price: 250.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 27,
      restaurantId: 6,
      name: 'Beef Mandhi',
      description: 'Traditional Arabian rice dish with tender beef',
      price: 350.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 28,
      restaurantId: 6,
      name: 'Chicken Mandhi',
      description: 'Traditional Arabian rice dish with tender chicken',
      price: 320.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 29,
      restaurantId: 6,
      name: 'Alpham',
      description: 'Spicy and flavorful meat and vegetable dish',
      price: 280.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 30,
      restaurantId: 7,
      name: 'Chicken Shawarma',
      description: 'Grilled chicken wrapped in a flatbread',
      price: 200.0,
      category: 'Shawarma',
    ),
    const MenuItem(
      id: 31,
      restaurantId: 7,
      name: 'Beef Shawarma',
      description: 'Grilled beef wrapped in a flatbread',
      price: 220.0,
      category: 'Shawarma',
    ),
    const MenuItem(
      id: 32,
      restaurantId: 7,
      name: 'Paneer Shawarma',
      description: 'Grilled paneer (cottage cheese) wrapped in a flatbread',
      price: 180.0,
      category: 'Shawarma',
    ),
    const MenuItem(
      id: 33,
      restaurantId: 7,
      name: 'Veggie Roll',
      description: 'Assorted vegetables wrapped in a flatbread',
      price: 150.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 34,
      restaurantId: 7,
      name: 'Chicken Roll',
      description: 'Grilled chicken wrapped in a flatbread',
      price: 180.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 35,
      restaurantId: 7,
      name: 'Beef Roll',
      description: 'Grilled beef wrapped in a flatbread',
      price: 200.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 36,
      restaurantId: 7,
      name: 'Coca-Cola',
      description: 'Classic cola beverage',
      price: 50.0,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 37,
      restaurantId: 7,
      name: 'Sprite',
      description: 'Lemon-lime flavored soda',
      price: 50.0,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 38,
      restaurantId: 9,
      name: 'Manchurian',
      description: 'Stir-fried vegetable or meat balls in a tangy sauce',
      price: 200.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 39,
      restaurantId: 9,
      name: 'Fried Rice',
      description: 'Stir-fried rice with vegetables and choice of protein',
      price: 180.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 40,
      restaurantId: 9,
      name: 'Noodles',
      description: 'Stir-fried noodles with vegetables and choice of protein',
      price: 190.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 41,
      restaurantId: 9,
      name: 'Butter Chicken',
      description: 'Tandoori chicken cooked in a creamy tomato-based sauce',
      price: 280.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 42,
      restaurantId: 9,
      name: 'Paneer Tikka Masala',
      description:
          'Grilled paneer (cottage cheese) in a spiced tomato-based sauce',
      price: 250.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 43,
      restaurantId: 9,
      name: 'Dal Makhani',
      description: 'Slow-cooked lentils in a rich and creamy sauce',
      price: 220.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 44,
      restaurantId: 8,
      name: 'Gulab Jamun',
      description: 'Deep-fried sweet dumplings in sugar syrup',
      price: 80.0,
      category: 'Deserts',
    ),
    const MenuItem(
      id: 45,
      restaurantId: 8,
      name: 'Rasmalai',
      description: 'Soft cottage cheese dumplings in sweet milk syrup',
      price: 100.0,
      category: 'Deserts',
    ),
    const MenuItem(
      id: 46,
      restaurantId: 8,
      name: 'Chocolate Brownie',
      description: 'Rich and fudgy chocolate brownie served with ice cream',
      price: 120.0,
      category: 'Deserts',
    ),
    const MenuItem(
      id: 47,
      restaurantId: 8,
      name: 'Iced Coffee',
      description: 'Chilled coffee with milk and ice',
      price: 90.0,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 48,
      restaurantId: 8,
      name: 'Mango Lassi',
      description: 'Refreshing yogurt-based drink with mango flavor',
      price: 80.0,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 49,
      restaurantId: 8,
      name: 'Lemonade',
      description: 'Classic citrusy and refreshing lemonade',
      price: 70.0,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 50,
      restaurantId: 8,
      name: 'Classic Cheeseburger',
      description: 'Juicy beef patty with cheese, lettuce, and tomato',
      price: 180.0,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 51,
      restaurantId: 8,
      name: 'Veggie Burger',
      description: 'Grilled vegetable patty with lettuce and mayo',
      price: 160.0,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 52,
      restaurantId: 8,
      name: 'Chicken Burger',
      description: 'Grilled chicken patty with lettuce and mayo',
      price: 190.0,
      category: 'Burgers',
    ),
    const MenuItem(
      id: 53,
      restaurantId: 8,
      name: 'Veggie Roll',
      description: 'Assorted vegetables wrapped in a flatbread',
      price: 150.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 54,
      restaurantId: 8,
      name: 'Chicken Roll',
      description: 'Grilled chicken wrapped in a flatbread',
      price: 180.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 55,
      restaurantId: 8,
      name: 'Paneer Roll',
      description: 'Grilled paneer (cottage cheese) wrapped in a flatbread',
      price: 170.0,
      category: 'Rolls',
    ),
    const MenuItem(
      id: 56,
      restaurantId: 8,
      name: 'Margherita Pizza',
      description: 'Classic cheese and tomato pizza',
      price: 200.0,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 57,
      restaurantId: 8,
      name: 'Pepperoni Pizza',
      description: 'Pizza with pepperoni toppings',
      price: 220.0,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 58,
      restaurantId: 8,
      name: 'Vegetarian Pizza',
      description: 'Pizza with assorted vegetables',
      price: 210.0,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 59,
      restaurantId: 9,
      name: 'Beef Mandhi',
      description: 'Traditional Arabian rice dish with tender beef',
      price: 350.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 60,
      restaurantId: 9,
      name: 'Chicken Mandhi',
      description: 'Traditional Arabian rice dish with tender chicken',
      price: 320.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 61,
      restaurantId: 9,
      name: 'Alpham',
      description: 'Spicy and flavorful meat and vegetable dish',
      price: 280.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 62,
      restaurantId: 10,
      name: 'Manchurian',
      description: 'Stir-fried vegetable or meat balls in a tangy sauce',
      price: 200.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 63,
      restaurantId: 10,
      name: 'Fried Rice',
      description: 'Stir-fried rice with vegetables and choice of protein',
      price: 180.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 64,
      restaurantId: 10,
      name: 'Noodles',
      description: 'Stir-fried noodles with vegetables and choice of protein',
      price: 190.0,
      category: 'Chinese',
    ),
    const MenuItem(
      id: 65,
      restaurantId: 10,
      name: 'Butter Chicken',
      description: 'Tandoori chicken cooked in a creamy tomato-based sauce',
      price: 280.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 66,
      restaurantId: 10,
      name: 'Paneer Tikka Masala',
      description:
          'Grilled paneer (cottage cheese) in a spiced tomato-based sauce',
      price: 250.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 67,
      restaurantId: 10,
      name: 'Dal Makhani',
      description: 'Slow-cooked lentils in a rich and creamy sauce',
      price: 220.0,
      category: 'North Indian',
    ),
    const MenuItem(
      id: 68,
      restaurantId: 10,
      name: 'Beef Mandhi',
      description: 'Traditional Arabian rice dish with tender beef',
      price: 350.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 69,
      restaurantId: 10,
      name: 'Chicken Mandhi',
      description: 'Traditional Arabian rice dish with tender chicken',
      price: 320.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 70,
      restaurantId: 10,
      name: 'Alpham',
      description: 'Spicy and flavorful meat and vegetable dish',
      price: 280.0,
      category: 'Arabian',
    ),
    const MenuItem(
      id: 71,
      restaurantId: 11,
      name: 'Pizza Margherita',
      description: 'Classic cheese and tomato pizza',
      price: 299.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 72,
      restaurantId: 11,
      name: 'Pizza Pepperoni',
      description: 'Pizza with pepperoni toppings',
      price: 349.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 73,
      restaurantId: 11,
      name: 'Pizza Vegetarian',
      description: 'Pizza with assorted vegetables',
      price: 249.99,
      category: 'Pizza',
    ),
    const MenuItem(
      id: 74,
      restaurantId: 11,
      name: 'Coca-Cola',
      description: 'Classic cola beverage',
      price: 50.99,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 75,
      restaurantId: 11,
      name: 'Sprite',
      description: 'Lemon-lime flavored soda',
      price: 50.99,
      category: 'Drinks',
    ),
    const MenuItem(
      id: 3,
      restaurantId: 1,
      name: 'Baviera',
      category: 'Pizza',
      description: 'Tomatoes, mozzarella, basil',
      price: 4.99,
    ),
    const MenuItem(
      id: 4,
      restaurantId: 1,
      name: 'Baviera',
      category: 'Pizza',
      description: 'Tomatoes, mozzarella, basil',
      price: 4.99,
    ),
    const MenuItem(
      id: 5,
      restaurantId: 1,
      name: 'Coca Cola',
      category: 'Drink',
      description: 'A fresh drink',
      price: 1.99,
    ),
    const MenuItem(
      id: 6,
      restaurantId: 1,
      name: 'Coca Cola',
      category: 'Drink',
      description: 'A fresh drink',
      price: 1.99,
    ),
    const MenuItem(
      id: 7,
      restaurantId: 2,
      name: 'Coca Cola',
      category: 'Drink',
      description: 'A fresh drink',
      price: 1.99,
    ),
    const MenuItem(
      id: 8,
      restaurantId: 3,
      name: 'Water',
      category: 'Drink',
      description: 'A fresh drink',
      price: 1.99,
    ),
    const MenuItem(
      id: 9,
      restaurantId: 2,
      name: 'Caesar Salad',
      category: 'Salad',
      description: 'A fresh drink',
      price: 1.99,
    ),
    const MenuItem(
      id: 10,
      restaurantId: 3,
      name: 'CheeseBurger',
      category: 'Burger',
      description: 'A burger with Cheese',
      price: 9.99,
    ),
    const MenuItem(
      id: 11,
      restaurantId: 4,
      name: 'Chocolate Cake',
      category: 'Desser',
      description: 'A cake with chocolate',
      price: 9.99,
    )
  ];
}
